services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ${APP_CONTAINER_NAME}
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=${APP_ENV}
            - APP_DEBUG=${APP_DEBUG}
            - APP_URL=${APP_URL}
